version: 0.2

phases:
  install:
    commands:
      - echo "Updating package lists..."
      - sudo apt-get update -y
      - sudo apt-get install -y nginx

  build:
    commands:
      - echo "Listing files..."
      - ls -la
      - echo "Removing any existing dist file if exists..."
      - rm -rf dist
      - echo "Creating dist directory..."
      - mkdir -p dist
      - echo "Copying files to dist/..."
      - cp -r * dist/
      - echo "Copying index.html to /var/www/html/..."
      - sudo cp index.html /var/www/html/

  post_build:
    commands:
      - echo "Restarting Nginx..."
      - sudo service nginx restart

artifacts:
  files:
    - '**/*'
  base-directory: dist

