version: 0.2

phases:
  install:
    commands:
      - echo "Updating package lists..."
      - apt-get update -y
      - echo "Installing Nginx..."
      - apt-get install -y nginx

  build:
    commands:
      - echo "Build started on $(date)"
      - echo "Checking if index.html exists..."
      - ls -la
      - if [ -f index.html ]; then echo "index.html found!"; else echo "index.html NOT found!"; exit 1; fi
      - echo "Copying index.html to /var/www/html/..."
      - sudo cp index.html /var/www/html/

  post_build:
    commands:
      - echo "Restarting Nginx..."
      - sudo service nginx restart

artifacts:
  files:
    - /var/www/html/index.html



