version: 0.2

phases:
  install:
    commands:
      - echo No dependencies to install

  build:
    commands:
      - echo Copying HTML files to the build output directory...
      - mkdir -p dist
      - cp index.html dist/

artifacts:
  files:
    - dist/*
  base-directory: dist  # Point to the folder with your HTML file
