version: 0.2

phases:
  install:
    commands:
      - echo "Updating package lists..."
      - apt-get update -y
      - echo "Installing Nginx..."
      - apt-get install -y nginx
      - echo "Starting Nginx..."
      - service nginx start

  build:
    commands:
      - echo "Creating dist directory..."
      - mkdir -p /var/www/html
      - echo "Copying HTML files..."
      - cp -v *.html /var/www/html/

  post_build:
    commands:
      - echo "Restarting Nginx to apply changes..."
      - service nginx restart

artifacts:
  files:
    - '**/*'
