version: 0.2

phases:
  install:
    commands:
      - echo "Updating package lists..."
      - apt-get update -y
      - echo "Installing Nginx..."
      - apt-get install -y nginx
      - echo "Starting Nginx..."
      - service nginx start

  build:
    commands:
      - echo "Checking working directory and files..."
      - pwd
      - ls -la
      - mkdir -p /var/www/html
      - echo "Copying HTML files..."
      - if ls *.html 1> /dev/null 2>&1; then cp -v *.html /var/www/html/; else echo "No HTML files found!"; fi

  post_build:
    commands:
      - echo "Restarting Nginx..."
      - service nginx restart

artifacts:
  files:
    - '**/*'
