version: 0.2

phases:
  install:
    commands:
      - echo "Updating package lists..."
      - apt-get update -y
      - sudo apt-get install -y nginx -y

  build:
    commands:
      -echo Build started on 'date'
      -cp index.html /var/www/html/

  post_build:
    commands:
      - echo "Restarting Nginx..."
artifacts:
  files:
    - /var/www/html/index.html

