version: 0.2

phases:
  install:
    commands:
      - echo "Updating package lists..."
      - apt-get update -y
      - echo "Installing Nginx..."
      - apt-get install -y nginx
      - echo "Starting Nginx..."
      - service nginx start

  build:
    commands:
      - echo "Checking if index.html exists..."
      - ls -la
      - if [ -f index.html ]; then echo "index.html found!"; else echo "index.html NOT found!"; exit 1; fi
      - echo "Ensuring /var/www/html exists..."
      - mkdir -p /var/www/html
      - echo "Copying index.html to /var/www/html..."
      - cp -v index.html /var/www/html/

  post_build:
    commands:
      - echo "Restarting Nginx..."
      - service nginx restart

artifacts:
  files:
    - '**/*'

