version: 0.2

phases:
  install:
    commands:
      - echo "Updating package lists..."
      - sudo apt-get update -y
      - sudo apt-get install -y nginx

  build:
    commands:
      - echo "Build started on $(date)"
      - cp index.html /var/www/html/

  post_build:
    commands:
      - echo "Restarting Nginx..."
      - sudo service nginx restart

artifacts:
  files:
    - /var/www/html/index.html
